// Generated by CoffeeScript 1.7.1
(function() {
  var db, mongoose;

  mongoose = require('mongoose');

  mongoose.connect('mongodb://localhost/shortly');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  module.exports = db;

}).call(this);

//# sourceMappingURL=config.map
