// Generated by CoffeeScript 1.7.1
(function() {
  var Link, crypto, mongoose, schemas, urlSchema;

  mongoose = require('mongoose');

  schemas = require('../config');

  crypto = require('crypto');

  urlSchema = schemas.urlSchema;

  Link = mongoose.model('Link', urlSchema);


  /*urlSchema.pre 'init', (next) ->
    shasum = crypto.createHash 'sha1'
    console.log this
   */

  module.exports = Link;

}).call(this);

//# sourceMappingURL=link.map
