// Generated by CoffeeScript 1.7.1
(function() {
  var Link, Schema, crypto, mongoose, urlSchema;

  mongoose = require('mongoose');

  crypto = require('crypto');

  Schema = mongoose.Schema;

  urlSchema = new Schema({
    url: String,
    base_url: String,
    code: String,
    title: String,
    visits: {
      type: Number,
      "default": 0
    },
    createdAt: {
      type: Date,
      "default": Date.now
    }
  });

  urlSchema.pre('save', function(next) {
    var shasum;
    shasum = crypto.createHash('sha1');
    shasum.update(this.url);
    this.code = (shasum.digest('hex')).slice(0, 5);
    return next();
  });

  Link = mongoose.model('Link', urlSchema);

  module.exports = Link;

}).call(this);

//# sourceMappingURL=link.map
