// Generated by CoffeeScript 1.7.1
(function() {
  var User, bcrypt, mongoose, schemas, userSchema;

  mongoose = require('mongoose');

  schemas = require('../config');

  bcrypt = require('bcrypt-nodejs');

  userSchema = schemas.userSchema;

  User = mongoose.model('User', userSchema);

  module.exports = User;

}).call(this);

//# sourceMappingURL=user.map
